[build]
builder = "nixpacks"
buildCommand = "pnpm install --ignore-workspace && pnpm build"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/api/panics"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
